import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='w-full h-full'>
      <body className={`${inter.className} w-full h-full`}>
        <div className='flex justify-between px-20 py-4'>
          <Link href='/'>Home</Link>
          <Link href='/about'>About</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
